apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rsapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rsapp
  template:
    metadata:
      name: rsapp
      labels:
        app: rsapp
    spec:
      containers:
      - name: app
        image: tuanld/java:1.0
        resources:
          limits:
            memory: "256Mi"
            cpu: "300m"
        ports:
          - containerPort: 8080
