apiVersion: v1
kind: Service
metadata:
  name: svc3
spec:
  selector:
     app: deployapp
  type: LoadBalancer
  loadBalancerIP: 35.225.32.106
  ports:
    - name: port1
      port: 8080
      targetPort: 8080